fix(k8s-intf): Fix LegalValue<GatewayAgentSpec> duplicate VPC ids issue
Fuzzing test
converters::k8s::config::overlay::test::test_overlay_conversion has been
caught failing due to a duplicated VPC id:

    Error:
    panicked at config/src/converters/k8s/config/overlay.rs:104:55:
    called `Result::unwrap()` on an `Err` value: InternalError("Cannot add vpc vpc1: A VPC with id 'aaaaa' already exists")
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

This can be reproduced with:

    $ BOLERO_RANDOM_SEED=215043561514902173833823553673718402751 \
        just cargo nextest run -p dataplane-config overlay_conversion

Make sure we don't use duplicated VPC ids when building the
GatewayAgentSpec, by "incrementing" the id string if necessary.

Signed-off-by: Quentin Monnet <qmo@qmon.net>