bump: Upgrade npins
We had the following error for dependency updates:

    $ bash scripts/bump.sh
    ++ dirname scripts/bump.sh
    + pushd scripts/..
    /var/home/qmo/dev/dataplane /var/home/qmo/dev/dataplane
    + npins update
    Error: Failed to deserialize sources.json

    Caused by:
        Version 7 is too old, you need to run upgrade

To address it, we simply ran the following command and committed the
changes:

    $ npins upgrade

Signed-off-by: Quentin Monnet <qmo@qmon.net>