build(dpdk-sys): Ignore unnecessary transmutes from bindgen output
In preparation for bumping the Rust version to v1.93 in compile-env,
ignore unnecessary transmutes in the code generated with rust-bindgen.
We can remove this once bindgen no longer produces code that triggers
the warnings.

Sample compilation output observed in CI (with -D warnings) when trying
to bump the Rust version, without this change:

    error: unnecessary transmute
        --> /home/runner/_work/dataplane/dataplane/target/x86_64-unknown-linux-gnu/debug/build/dataplane-dpdk-sys-a41e4a6d599db730/out/generated.rs:1750:18
         |
    1750 |         unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
         |                  ----------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         |                  |
         |                  help: replace this with: `u32::cast_signed`
         |
         = note: `-D unnecessary-transmutes` implied by `-D warnings`
         = help: to override `-D warnings` add `#[allow(unnecessary_transmutes)]`

    error: unnecessary transmute
        --> /home/runner/_work/dataplane/dataplane/target/x86_64-unknown-linux-gnu/debug/build/dataplane-dpdk-sys-a41e4a6d599db730/out/generated.rs:1755:28
         |
    1755 |             let val: u32 = ::core::mem::transmute(val);
         |                            ----------------------^^^^^
         |                            |
         |                            help: replace this with: `i32::cast_unsigned`

    error: unnecessary transmute
        --> /home/runner/_work/dataplane/dataplane/target/x86_64-unknown-linux-gnu/debug/build/dataplane-dpdk-sys-a41e4a6d599db730/out/generated.rs:1762:13
         |
    1762 |               ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 3usize]>>::raw_get(
         |               ^---------------------
         |               |
         |  _____________help: replace this with: `u32::cast_signed`
         | |
    1763 | |                 ::core::ptr::addr_of!((*this)._bitfield_1),
    1764 | |                 0usize,
    1765 | |                 24u8,
    1766 | |             ) as u32)
         | |_____________________^

    error: unnecessary transmute
        --> /home/runner/_work/dataplane/dataplane/target/x86_64-unknown-linux-gnu/debug/build/dataplane-dpdk-sys-a41e4a6d599db730/out/generated.rs:1772:28
         |
    1772 |             let val: u32 = ::core::mem::transmute(val);
         |                            ----------------------^^^^^
         |                            |
         |                            help: replace this with: `i32::cast_unsigned`

    error: unnecessary transmute
        --> /home/runner/_work/dataplane/dataplane/target/x86_64-unknown-linux-gnu/debug/build/dataplane-dpdk-sys-a41e4a6d599db730/out/generated.rs:1785:41
         |
    1785 |             let _flags2: u32 = unsafe { ::core::mem::transmute(_flags2) };
         |                                         ----------------------^^^^^^^^^
         |                                         |
         |                                         help: replace this with: `i32::cast_unsigned`

Signed-off-by: Quentin Monnet <qmo@qmon.net>