chore: Pin minor version number for smallvec
The latest minor version for smallvec creates a conflict:

  [ERROR] failed to fetch crates:     Updating crates.io index
  error: failed to select a version for `smallvec`.
      ... required by package `serde-saphyr v0.0.29`
      ... which satisfies dependency `serde-saphyr = "^0.0.29"` of package `kube-client v4.2.0`
      ... which satisfies dependency `kube-client = "=4.2.0"` of package `kube v4.2.0`
      ... which satisfies dependency `kube = "^4.2.0"` of package `dataplane-k8s-intf v0.29.0
      ... which satisfies path dependency `k8s-intf` (locked to 0.29.0) of package `dataplane-validator v0.29.0
  versions that meet the requirements `>=1.0.0, <1.16.0` are: 1.15.2, [...]

  all possible versions conflict with previously selected packages

    previously selected package `smallvec v1.16.2`
      ... which satisfies dependency `smallvec = "^1.16.2"` of package `dataplane-nat v0.29.0
      ... which satisfies path dependency `nat` (locked to 0.29.0) of package `dataplane v0.29.0

Pin the minor version to avoid attempts to bump to 1.16+ on automated
upgrades.

Signed-off-by: Quentin Monnet <qmo@qmon.net>